---
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  linter:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run Ansible Linter
        uses: ansible/ansible-lint-action@v4.1.0
        with:
          targets: "*"
